/***** DO NOT EDIT THIS FILE *****/
// TLandDemoCSVJUNE3.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var TLandDemoCSVJUNE3 = {};

/*** script -- CSV ***/
TLandDemoCSVJUNE3.CSV = function(app) {
	MT.Script.call(this, app, "CSV.mt");
};

TLandDemoCSVJUNE3.CSV.prototype = new MT.Script;

TLandDemoCSVJUNE3.CSV.prototype.call = function() {
	//run: CSV.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.cSV = function() {
	return new TLandDemoCSVJUNE3.CSV(this);
};

/*** script -- CSV2 ***/
TLandDemoCSVJUNE3.CSV2 = function(app) {
	MT.Script.call(this, app, "CSV2.mt");
};

TLandDemoCSVJUNE3.CSV2.prototype = new MT.Script;

TLandDemoCSVJUNE3.CSV2.prototype.call = function(Ccell, Qquestion, Achoice, Bchoice, Cchoice, Danswer) {
	//run: CSV2.mt
	MT.Script.prototype.call(this, Ccell, Qquestion, Achoice, Bchoice, Cchoice, Danswer);
};

MT.Application.prototype.cSV2 = function() {
	return new TLandDemoCSVJUNE3.CSV2(this);
};

/*** script -- ExhibittoTrivia ***/
TLandDemoCSVJUNE3.ExhibittoTrivia = function(app) {
	MT.Script.call(this, app, "ExhibittoTrivia.mt");
};

TLandDemoCSVJUNE3.ExhibittoTrivia.prototype = new MT.Script;

TLandDemoCSVJUNE3.ExhibittoTrivia.prototype.call = function() {
	//run: ExhibittoTrivia.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.exhibittoTrivia = function() {
	return new TLandDemoCSVJUNE3.ExhibittoTrivia(this);
};

/*** script -- Trivia2Question2Answer2Back2Trivia ***/
TLandDemoCSVJUNE3.Trivia2Question2Answer2Back2Trivia = function(app) {
	MT.Script.call(this, app, "Trivia2Question2Answer2Back2Trivia.mt");
};

TLandDemoCSVJUNE3.Trivia2Question2Answer2Back2Trivia.prototype = new MT.Script;

TLandDemoCSVJUNE3.Trivia2Question2Answer2Back2Trivia.prototype.call = function(Q, A, B, C) {
	//run: Trivia2Question2Answer2Back2Trivia.mt
	MT.Script.prototype.call(this, Q, A, B, C);
};

MT.Application.prototype.trivia2Question2Answer2Back2Trivia = function() {
	return new TLandDemoCSVJUNE3.Trivia2Question2Answer2Back2Trivia(this);
};

