/***** DO NOT EDIT THIS FILE *****/
// TLand.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var TLand = {};

/*** script -- Sanity ***/
TLand.Sanity = function(app) {
	MT.Script.call(this, app, "Sanity.mt");
};

TLand.Sanity.prototype = new MT.Script;

TLand.Sanity.prototype.call = function() {
	//run: Sanity.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.sanity = function() {
	return new TLand.Sanity(this);
};

/*** script -- Sanity2 ***/
TLand.Sanity2 = function(app) {
	MT.Script.call(this, app, "Sanity2.mt");
};

TLand.Sanity2.prototype = new MT.Script;

TLand.Sanity2.prototype.call = function() {
	//run: Sanity2.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.sanity2 = function() {
	return new TLand.Sanity2(this);
};

/*** script -- sanity3 ***/
TLand.sanity3 = function(app) {
	MT.Script.call(this, app, "sanity3.mt");
};

TLand.sanity3.prototype = new MT.Script;

TLand.sanity3.prototype.call = function() {
	//run: sanity3.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.sanity3 = function() {
	return new TLand.sanity3(this);
};

