/***** DO NOT EDIT THIS FILE *****/
// MonkeyProjectSanta.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var MonkeyProjectSanta = {};

/*** script -- MemoryMatch2 ***/
MonkeyProjectSanta.MemoryMatch2 = function(app) {
	MT.Script.call(this, app, "MemoryMatch2.mt");
};

MonkeyProjectSanta.MemoryMatch2.prototype = new MT.Script;

MonkeyProjectSanta.MemoryMatch2.prototype.call = function() {
	//run: MemoryMatch2.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.memoryMatch2 = function() {
	return new MonkeyProjectSanta.MemoryMatch2(this);
};

/*** script -- MonkeyProjectTest ***/
MonkeyProjectSanta.MonkeyProjectTest = function(app) {
	MT.Script.call(this, app, "MonkeyProjectTest.mt");
};

MonkeyProjectSanta.MonkeyProjectTest.prototype = new MT.Script;

MonkeyProjectSanta.MonkeyProjectTest.prototype.call = function() {
	//run: MonkeyProjectTest.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.monkeyProjectTest = function() {
	return new MonkeyProjectSanta.MonkeyProjectTest(this);
};

/*** script -- SnowGlobe1 ***/
MonkeyProjectSanta.SnowGlobe1 = function(app) {
	MT.Script.call(this, app, "SnowGlobe1.mt");
};

MonkeyProjectSanta.SnowGlobe1.prototype = new MT.Script;

MonkeyProjectSanta.SnowGlobe1.prototype.call = function() {
	//run: SnowGlobe1.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.snowGlobe1 = function() {
	return new MonkeyProjectSanta.SnowGlobe1(this);
};

