/***** DO NOT EDIT THIS FILE *****/
// MonkeyProjectSanta.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var MonkeyProjectSanta = {};

/*** script -- JetPack1 ***/
MonkeyProjectSanta.JetPack1 = function(app) {
	MT.Script.call(this, app, "JetPack1.mt");
};

MonkeyProjectSanta.JetPack1.prototype = new MT.Script;

MonkeyProjectSanta.JetPack1.prototype.call = function() {
	//run: JetPack1.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.jetPack1 = function() {
	return new MonkeyProjectSanta.JetPack1(this);
};

/*** script -- SantaTrackerMatchGame ***/
MonkeyProjectSanta.SantaTrackerMatchGame = function(app) {
	MT.Script.call(this, app, "SantaTrackerMatchGame.mt");
};

MonkeyProjectSanta.SantaTrackerMatchGame.prototype = new MT.Script;

MonkeyProjectSanta.SantaTrackerMatchGame.prototype.call = function() {
	//run: SantaTrackerMatchGame.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.santaTrackerMatchGame = function() {
	return new MonkeyProjectSanta.SantaTrackerMatchGame(this);
};

