/***** DO NOT EDIT THIS FILE *****/
// Viggle.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var Viggle = {};

/*** script -- MonkeyProjectViggle ***/
Viggle.MonkeyProjectViggle = function(app) {
	MT.Script.call(this, app, "MonkeyProjectViggle.mt");
};

Viggle.MonkeyProjectViggle.prototype = new MT.Script;

Viggle.MonkeyProjectViggle.prototype.call = function() {
	//run: MonkeyProjectViggle.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.monkeyProjectViggle = function() {
	return new Viggle.MonkeyProjectViggle(this);
};

/*** script -- ViggleChangePlayerbuttontest ***/
Viggle.ViggleChangePlayerbuttontest = function(app) {
	MT.Script.call(this, app, "ViggleChangePlayerbuttontest.mt");
};

Viggle.ViggleChangePlayerbuttontest.prototype = new MT.Script;

Viggle.ViggleChangePlayerbuttontest.prototype.call = function() {
	//run: ViggleChangePlayerbuttontest.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.viggleChangePlayerbuttontest = function() {
	return new Viggle.ViggleChangePlayerbuttontest(this);
};

