/***** DO NOT EDIT THIS FILE *****/
// MonkeyProjectSanta.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var MonkeyProjectSanta = {};

/*** script -- Santa111014 ***/
MonkeyProjectSanta.Santa111014 = function(app) {
	MT.Script.call(this, app, "Santa111014.mt");
};

MonkeyProjectSanta.Santa111014.prototype = new MT.Script;

MonkeyProjectSanta.Santa111014.prototype.call = function() {
	//run: Santa111014.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.santa111014 = function() {
	return new MonkeyProjectSanta.Santa111014(this);
};

