/***** DO NOT EDIT THIS FILE *****/
// TomorrowLandDemo.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var TomorrowLandDemo = {};

/*** script -- CSVQuestion ***/
TomorrowLandDemo.CSVQuestion = function(app) {
	MT.Script.call(this, app, "CSVQuestion.mt");
};

TomorrowLandDemo.CSVQuestion.prototype = new MT.Script;

TomorrowLandDemo.CSVQuestion.prototype.call = function() {
	//run: CSVQuestion.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.cSVQuestion = function() {
	return new TomorrowLandDemo.CSVQuestion(this);
};

/*** script -- Funfacts ***/
TomorrowLandDemo.Funfacts = function(app) {
	MT.Script.call(this, app, "Funfacts.mt");
};

TomorrowLandDemo.Funfacts.prototype = new MT.Script;

TomorrowLandDemo.Funfacts.prototype.call = function() {
	//run: Funfacts.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.funfacts = function() {
	return new TomorrowLandDemo.Funfacts(this);
};

/*** script -- TestSuiteExhibit ***/
TomorrowLandDemo.TestSuiteExhibit = function(app) {
	MT.Script.call(this, app, "TestSuiteExhibit.mt");
};

TomorrowLandDemo.TestSuiteExhibit.prototype = new MT.Script;

TomorrowLandDemo.TestSuiteExhibit.prototype.call = function() {
	//run: TestSuiteExhibit.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.testSuiteExhibit = function() {
	return new TomorrowLandDemo.TestSuiteExhibit(this);
};

/*** script -- TestSuiteTrivaQuestions ***/
TomorrowLandDemo.TestSuiteTrivaQuestions = function(app) {
	MT.Script.call(this, app, "TestSuiteTrivaQuestions.mt");
};

TomorrowLandDemo.TestSuiteTrivaQuestions.prototype = new MT.Script;

TomorrowLandDemo.TestSuiteTrivaQuestions.prototype.call = function() {
	//run: TestSuiteTrivaQuestions.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.testSuiteTrivaQuestions = function() {
	return new TomorrowLandDemo.TestSuiteTrivaQuestions(this);
};

/*** script -- TestSuiteTriviaIntro ***/
TomorrowLandDemo.TestSuiteTriviaIntro = function(app) {
	MT.Script.call(this, app, "TestSuiteTriviaIntro.mt");
};

TomorrowLandDemo.TestSuiteTriviaIntro.prototype = new MT.Script;

TomorrowLandDemo.TestSuiteTriviaIntro.prototype.call = function() {
	//run: TestSuiteTriviaIntro.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.testSuiteTriviaIntro = function() {
	return new TomorrowLandDemo.TestSuiteTriviaIntro(this);
};

/*** script -- TestSuiteTutorial ***/
TomorrowLandDemo.TestSuiteTutorial = function(app) {
	MT.Script.call(this, app, "TestSuiteTutorial.mt");
};

TomorrowLandDemo.TestSuiteTutorial.prototype = new MT.Script;

TomorrowLandDemo.TestSuiteTutorial.prototype.call = function() {
	//run: TestSuiteTutorial.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.testSuiteTutorial = function() {
	return new TomorrowLandDemo.TestSuiteTutorial(this);
};

/*** script -- TestSuiteTutorialSkip ***/
TomorrowLandDemo.TestSuiteTutorialSkip = function(app) {
	MT.Script.call(this, app, "TestSuiteTutorialSkip.mt");
};

TomorrowLandDemo.TestSuiteTutorialSkip.prototype = new MT.Script;

TomorrowLandDemo.TestSuiteTutorialSkip.prototype.call = function() {
	//run: TestSuiteTutorialSkip.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.testSuiteTutorialSkip = function() {
	return new TomorrowLandDemo.TestSuiteTutorialSkip(this);
};

