/***** DO NOT EDIT THIS FILE *****/
// TLandDemoCSV.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var TLandDemoCSV = {};

/*** script -- Questions ***/
TLandDemoCSV.Questions = function(app) {
	MT.Script.call(this, app, "Questions.mt");
};

TLandDemoCSV.Questions.prototype = new MT.Script;

TLandDemoCSV.Questions.prototype.call = function(question, answer) {
	//run: Questions.mt
	MT.Script.prototype.call(this, question, answer);
};

MT.Application.prototype.questions = function() {
	return new TLandDemoCSV.Questions(this);
};

