/***** DO NOT EDIT THIS FILE *****/
// MonkeyProjectSanta.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var MonkeyProjectSanta = {};

/*** script -- SnowGlobe1 ***/
MonkeyProjectSanta.SnowGlobe1 = function(app) {
	MT.Script.call(this, app, "SnowGlobe1.mt");
};

MonkeyProjectSanta.SnowGlobe1.prototype = new MT.Script;

MonkeyProjectSanta.SnowGlobe1.prototype.call = function() {
	//run: SnowGlobe1.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.snowGlobe1 = function() {
	return new MonkeyProjectSanta.SnowGlobe1(this);
};

